name: Windows 64bits installer

on:
  push:

  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout mod_harbour repo
      uses: actions/checkout@v2
            
    - name: Build installer
      run: |
        iscc windows/install_win64/modharbour.iss
          
