name: modharbour for Mac OSX

on:
  push:
    paths: 
      - 'apache.prg'
      - 'mod_harbour.c'
      - 'osx/modharbour.hbp'
      - 'osx/mod.hbp'
  watch:
   types: [started]

jobs:
  build:
    runs-on: macos-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout mod_harbour repo
      uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         brew install curl
         brew install pcre
         brew install httpd
         cd osx
         sed -i '' 's/anto/runner\/runners\/2.169.1\/work\/mod_harbour\/mod_harbour/g' libs.txt
         
    - name: Compile Harbour
      run: |
        cd harbour
        export HB_WITH_CURL=/usr/local/Cellar/curl/7.69.1/include/
        export HB_BUILD_CONTRIBS=""
        make
        
    - name: Compile mod_harbour
      run: |
        cd osx
        ../harbour/bin/darwin/clang/hbmk2 modharbour.hbp
        mv libmod_harbour.so mod_harbour.so
        
    - name: Upload mod_harbour.so to artifact
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_macos_dev
       path: osx/mod_harbour.so
       
    - name: Upload libharbour.so.3.2.0 to artifact
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_macos_dev
        path: osx/libharbour.3.2.0.dylib
        
    - name: Upload readme.md to artifact
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_macos_dev
        path: osx/readme.md
