name: macOS

on:
  push:
    branches: [master]
  watch:
   types: [started]

jobs:
  build:
    runs-on: macos-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout mod_harbour repo
      uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         brew install curl
         brew install pcre
         brew install httpd
         
    - name: Test
      run: |
        cd osx
        sed -i 's/anto/runner\/runners\/2.169.1\/work\/mod_harbour\/mod_harbour/g' libs.txt
        sed -i 's/8.43/8.44/g' libs.txt
        cat libs.txt
