name: modharbour for Ubuntu 64

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout mod_harbour repo
      uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt install libcurl4-openssl-dev libssl-dev apache2-dev gcc
         sudo cp -r /usr/include/x86_64-linux-gnu/curl /usr/include
         
    - name: Compile harbour
      run: |
        cd harbour
        export HB_USER_CFLAGS="-fPIC"
        export HB_BUILD_CONTRIBS
        export HB_WITH_PCRE=local
        make
    - name: Compile mod_harbour
      run: |
        cd linux
        ../harbour/bin/linux/gcc/hbmk2 modharbour.hbp
        mv libmod_harbour.so mod_harbour.so
        
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Upload mod_harbour.so to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_ubuntu64_${{ env.TIME }}
       path: linux/mod_harbour.so
       
    - name: Upload libharbour.so.3.2.0 to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_ubuntu64_${{ env.TIME }}
        path: linux/libharbour.so.3.2.0
        
    - name: Upload readme.md to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_ubuntu64_${{ env.TIME }}
        path: linux/readme.md
