name: modharbour IIS Win64 msvc

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - uses: actions/checkout@v2

    - name: Build mod_harbour solution
      shell: cmd
      run: |
        cd IIS
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        msbuild.exe mod_harbour.sln /p:Configuration=Release
        copy D:\a\mod_harbour\mod_harbour\IIS\x64\Release\mod_harbour.dll D:\a\mod_harbour\mod_harbour\IIS\bin\mod_harbour.dll
        copy D:\a\mod_harbour\mod_harbour\IIS\readme.md D:\a\mod_harbour\mod_harbour\IIS\bin
        
    - name: Get current date
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Building the final zip with mod_harbour, msvc redistributable and required DLLs inside
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_IIS_win64_${{ env.TIME }}
       path: D:\a\mod_harbour\mod_harbour\IIS\bin         
