name: Harbour for Win32 using msvc

on:
  push:
    paths: 
      - 'apache.prg'
      - 'mod_harbour.c'
      - 'windows/modharbour.hbp'
      - 'windows/mod.hbp'
      - '.github/workflows/modharbour_win32_msvc.yml'  
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout harbour/core repo
        uses: actions/checkout@v2
        with:
          repository: harbour/core
          path: harbour
  
      - name: Installing dependencies
        shell: cmd 
        run: |
          choco install apache-httpd --x86 --params '"/installLocation:C:"'
          vcpkg.exe install curl:x86-windows
          vcpkg.exe install openssl:x86-windows
          vcpkg integrate install
          
      - name: Fixing Harbour hbssl.hbp
        run: |
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'libeay32','libcrypto' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'ssleay32','libssl' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'libeay32','libcrypto-1_1-x32' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'ssleay32','libssl-1_1-x32' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc          

      - name: Compile Harbour
        shell: cmd
        run: |
          cd harbour
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          set HB_BUILD_MODE=c
          set HB_USER_PRGFLAGS=-l-
          set HB_BUILD_CONTRIBS=
          set HB_WITH_OPENSSL=c:\vcpkg\packages\openssl-windows_x86-windows\include\
          set HB_WITH_CURL=c:\vcpkg\packages\curl_x86-windows\include
          set HB_OPENSSL_STATIC=yes      
          set HB_STATIC_OPENSSL=yes  
          set HB_STATIC_CURL=yes
          set HB_BUILD_DYN=no
          set HB_BUILD_CONTRIB_DYN=no
          set HB_COMPILER=msvc
          win-make.exe        
          copy lib\win\msvc\libcrypto-1_1.lib lib\win\msvc\libeay32.lib
          copy lib\win\msvc\libssl-1_1.lib lib\win\msvc\ssleay32.lib
          
      - name: Compile mod_harbour
        shell: cmd
        run: |
          cd windows
          rem copy ..\mod_harbour\windows\win64\ap_missing\apr_perms_set.h c:\Apache24\Apache24\include
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          ..\harbour\bin\win\msvc\hbmk2 modharbour.hbp -comp=msvc -Lc:\Apache24\lib -Lc:\vcpkg\packages\curl_x86-windows\lib
        
      - name: Create output folders
        shell: cmd
        run: |
          mkdir output
          mkdir output\samples
          mkdir output\harbour
          copy .\windows\mod_harbour.so output
          copy .\windows\libharbour.dll output
          copy .\windows\readme.md output
          xcopy samples output\samples\ /E
          xcopy harbour output\harbour\ /E  
        
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY_MM_DD
 
      - name: Upload mod_harbour to artifact
        env:
           TIME: "${{ steps.current-time.outputs.formattedTime }}"
        uses: actions/upload-artifact@v2
        with:
          name: modharbour_win32_msvc_${{ env.TIME }}
          path: output
