name: modharbour IIS Win64 msvc

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build mod_harbour solution
      shell: cmd
      run: |  
        cd IIS
        msbuild.exe mod_harbour.sln 
    
    
