name: Harbour for Win64 using msvc and vcpkg

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout harbour/core repo
        uses: actions/checkout@v2
        with:
          repository: harbour/core
          path: harbour
  
      - name: Installing dependencies
        shell: cmd 
        run: |
          vcpkg.exe install curl:x64-windows
          vcpkg.exe install openssl:x64-windows
          vcpkg integrate install
          
      - name: Compile Harbour
        shell: cmd
        run: |
          cd harbour
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          set HB_BUILD_MODE=c
          set HB_USER_PRGFLAGS=-l-
          set HB_BUILD_CONTRIBS=
          set HB_WITH_OPENSSL=c:\vcpkg\packages\openssl-windows_x64-windows\include\
          set HB_WITH_CURL=c:\vcpkg\packages\curl_x64-windows\include
          set HB_OPENSSL_STATIC=yes        
          set HB_STATIC_CURL=yes
          set HB_BUILD_DYN=no
          set HB_BUILD_CONTRIB_DYN=no
          set HB_COMPILER=msvc64
          win-make.exe          
