name: modharbour for Win64 and msvc

on:
  push:
    paths: 
      - 'apache.prg'
      - 'mod_harbour.c'
      - 'windows/modharbour.hbp'
      - 'windows/mod.hbp'
      - '.github/workflows/modharbour_win64_msvc.yml'
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         choco install apache-httpd --params '"/installLocation:C:"'
         choco install openssl --params '"/installLocation:C:"'
         choco install curl --params '"/installLocation:C:"'
         (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace '/../inc32','' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
         Copy-Item c:\programdata\chocolatey\lib\curl\tools\curl-7.70.0-win64-mingw\lib\libcurl.a -Destination harbour\lib\win\msvc64\libcurl.lib
         
    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL="%ProgramFiles%"/OpenSSL-Win64/include
        set OPENSSL_CONF="c:\Program Files\OpenSSL-Win64\bin\openssl.cfg"
        set HB_WITH_CURL=c:/ProgramData/chocolatey/lib/curl/tools/curl-7.70.0-win64-mingw/include/
        set HB_OPENSSL_STATIC=        
        set HB_STATIC_CURL=no
        set HB_BUILD_DYN=no
        set HB_BUILD_CONTRIB_DYN=no
        set HB_COMPILER=msvc64
        win-make.exe
        
    - name: Compile mod_harbour
      shell: cmd
      run: |
        cd windows
        set oldpath=%Path%
        set oldinclude=%INCLUDE%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        ..\harbour\bin\win\msvc64\hbmk2 modharbour.hbp -comp=msvc64 -Lc:\Apache24\lib
        set Path=%oldpath%
        set INCLUDE=%oldinclude%
        
    - name: Create output folders
      shell: cmd
      run: |
        mkdir output
        mkdir output\samples
        copy .\windows\mod_harbour.so output
        copy .\windows\libharbour.dll output
        copy .\windows\readme.md output
        copy -r .\samples\* output\samples   
        
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Upload mod_harbour to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_win64_msvc_${{ env.TIME }}
       path: output
