name: Windows Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    
    steps:    
    - name: My Tests
      shell: cmd
      run: |
         dir c:\%ProgramFiles(x86)%
      
