name: Windows x64 CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    
    - name: Install dependencies
      run: |
         (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/harbour_and_xharbour_builds/blob/master/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
         cd C:\temp
         Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL
         dir "C:"
         dir "C:\temp"
         
      
