name: Windows x64 CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         choco install apache-httpd --params '"/installLocation:C:\"'
         choco install visualstudio2019community
         choco install curl
         choco install openssl
         
    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL="c:\Program Files\OpenSSL-Win64\include"
        set HB_WITH_CURL=c:\curl\include
        del .\src\common\obj\win\msvc64\hbver.obj
        del .\src\common\obj\win\msvc64\hbver_dyn.obj
        del .\src\common\obj\win\msvc64\hbverdsp.obj
        win-make.exe
      
    - name: Compile mod_harbour
      shell: cmd
      run: |
        cd windows
        @set oldpath=%Path%
        @set oldinclude=%INCLUDE%
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        ..\harbour\bin\win\msvc64\hbmk2 modharbour.hbp -comp=msvc64 -Lc:\Apache24\lib
        @set Path=%oldpath%
        @set INCLUDE=%oldinclude%
      
