name: Windows 32-bits with ADS

on:
  push:
    paths: 
      - 'apache.prg'
      - 'mod_harbour.c'
      - 'windows/modharbour.hbp'
      - 'windows/mod.hbp'
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         choco install apache-httpd --x86 --params '"/installLocation:C:"'
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
         Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
         Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/acesdk.zip', 'C:\temp\acesdk.zip')
         Expand-Archive -LiteralPath C:\temp\acesdk.zip -DestinationPath C:\acesdk -Force
         
    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=C:\OpenSSL\include
        set HB_WITH_CURL=C:\curl\include
        set HB_WITH_ADS=C:\acesdk
        set HB_COMPILER=msvc
        del .\src\common\obj\win\msvc\hbver.obj
        del .\src\common\obj\win\msvc\hbver_dyn.obj
        del .\src\common\obj\win\msvc\hbverdsp.obj
        win-make.exe
        
    - name: Compile mod_harbour
      shell: cmd
      run: |
        cd windows
        set oldpath=%Path%
        set oldinclude=%INCLUDE%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
        ..\harbour\bin\win\msvc\hbmk2 modharbour.hbp -comp=msvc -Lc:\Apache24\lib -dHB_WITH_ADS="c:\acesdk\" rddads.hbc
        set Path=%oldpath%
        set INCLUDE=%oldinclude%
        
    - name: Upload mod_harbour.so to artifact
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_win32ads_dev
       path: windows/mod_harbour.so
       
    - name: Upload libharbour.dll to artifact
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_win32ads_dev
        path: windows/libharbour.dll

    - name: Upload readme.md to artifact
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_win32ads_dev
        path: windows/readme.md
