name: Windows Test

on:
  push:
    paths: 
      - 'apache.prg'
      - 'mod_harbour.c'
      - 'windows/modharbour.hbp'
      - 'windows/mod.hbp'
      - '.github/workflows/windows_test.yml'
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         choco install apache-httpd --params '"/installLocation:C:"'
         choco install openssl --x86
         choco install curl --x86
         Copy-Item 'C:\Program Files\OpenSSL-Win32' 'C:\OpenSSL-Win32' -Recurse
         Copy-Item 'C:\ProgramData\chocolatey\lib\curl\tools\curl-7.70.0-win32-mingw' 'C:\curl' -Recurse
    
    - name: Checks
      run: |
        dir C:\OpenSSL-Win32\
        dir C:\OpenSSL-Win32\lib
        dir C:\OpenSSL-Win32\include
        dir kjnfdjkfn

    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=C:\OpenSSL-Win64\include
        set HB_WITH_CURL=C:\curl\include
        set HB_COMPILER=msvc64
        del .\src\common\obj\win\msvc64\hbver.obj
        del .\src\common\obj\win\msvc64\hbver_dyn.obj
        del .\src\common\obj\win\msvc64\hbverdsp.obj
        win-make.exe
        
    - name: Compile mod_harbour
      shell: cmd
      run: |
        cd windows
        set oldpath=%Path%
        set oldinclude=%INCLUDE%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        ..\harbour\bin\win\msvc64\hbmk2 modharbour.hbp -comp=msvc64 -Lc:\Apache24\lib
        set Path=%oldpath%
        set INCLUDE=%oldinclude%
        
    - name: Upload mod_harbour.so to artifact
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_win64_dev
       path: windows/mod_harbour.so
       
    - name: Upload libharbour.dll to artifact
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_win64_dev
        path: windows/libharbour.dll

    - name: Upload readme.md to artifact
      uses: actions/upload-artifact@v2
      with:
        name: modharbour_win64_dev
        path: windows/readme.md
