name: Windows x64 CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         choco install apache-httpd --params '"/installLocation:C:"'
         choco install curl
         choco install openssl --x86
         (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/harbour_and_xharbour_builds/raw/master/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
         Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
         (new-object System.Net.WebClient).DownloadFile('https://api.zop.yt/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
         Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
         
    - name: Tests
      run: |
        dir C:\curl
         
    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=C:\OpenSSL\include
        set HB_WITH_CURL=C:\curl\include
        set HB_COMPILER=msvc64
        del .\src\common\obj\win\msvc64\hbver.obj
        del .\src\common\obj\win\msvc64\hbver_dyn.obj
        del .\src\common\obj\win\msvc64\hbverdsp.obj
        win-make.exe
        
    - name: Compile mod_harbour
      shell: cmd
      run: |
        cd windows
        set oldpath=%Path%
        set oldinclude=%INCLUDE%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        ..\harbour\bin\win\msvc64\hbmk2 modharbour.hbp -comp=msvc64 -Lc:\Apache24\lib
        set Path=%oldpath%
        set INCLUDE=%oldinclude%
      
