name: Windows x64 CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: C:\harbour

    - name: Install dependencies
      run: |
         choco install apache-httpd --params '"/installLocation:C:\Apache24"'
         
    - name: Windows test
      run: |
         dir
         dir c:
